// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef PROTOBUF_config_2eproto__INCLUDED
#define PROTOBUF_config_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace test {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_config_2eproto();
void protobuf_AssignDesc_config_2eproto();
void protobuf_ShutdownFile_config_2eproto();

class first;

// ===================================================================

class first : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.first) */ {
 public:
  first();
  virtual ~first();

  first(const first& from);

  inline first& operator=(const first& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const first& default_instance();

  void Swap(first* other);

  // implements Message ----------------------------------------------

  inline first* New() const { return New(NULL); }

  first* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const first& from);
  void MergeFrom(const first& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(first* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // optional uint32 b = 2;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::uint32 b() const;
  void set_b(::google::protobuf::uint32 value);

  // optional string c = 3;
  bool has_c() const;
  void clear_c();
  static const int kCFieldNumber = 3;
  const ::std::string& c() const;
  void set_c(const ::std::string& value);
  void set_c(const char* value);
  void set_c(const char* value, size_t size);
  ::std::string* mutable_c();
  ::std::string* release_c();
  void set_allocated_c(::std::string* c);

  // repeated uint32 d = 4;
  int d_size() const;
  void clear_d();
  static const int kDFieldNumber = 4;
  ::google::protobuf::uint32 d(int index) const;
  void set_d(int index, ::google::protobuf::uint32 value);
  void add_d(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      d() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_d();

  // @@protoc_insertion_point(class_scope:test.first)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();
  inline void set_has_c();
  inline void clear_has_c();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::uint32 b_;
  ::google::protobuf::internal::ArenaStringPtr c_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > d_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();

  void InitAsDefaultInstance();
  static first* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// first

// required int32 a = 1;
inline bool first::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void first::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void first::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void first::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 first::a() const {
  // @@protoc_insertion_point(field_get:test.first.a)
  return a_;
}
inline void first::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:test.first.a)
}

// optional uint32 b = 2;
inline bool first::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void first::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void first::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void first::clear_b() {
  b_ = 0u;
  clear_has_b();
}
inline ::google::protobuf::uint32 first::b() const {
  // @@protoc_insertion_point(field_get:test.first.b)
  return b_;
}
inline void first::set_b(::google::protobuf::uint32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:test.first.b)
}

// optional string c = 3;
inline bool first::has_c() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void first::set_has_c() {
  _has_bits_[0] |= 0x00000004u;
}
inline void first::clear_has_c() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void first::clear_c() {
  c_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_c();
}
inline const ::std::string& first::c() const {
  // @@protoc_insertion_point(field_get:test.first.c)
  return c_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void first::set_c(const ::std::string& value) {
  set_has_c();
  c_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:test.first.c)
}
inline void first::set_c(const char* value) {
  set_has_c();
  c_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:test.first.c)
}
inline void first::set_c(const char* value, size_t size) {
  set_has_c();
  c_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:test.first.c)
}
inline ::std::string* first::mutable_c() {
  set_has_c();
  // @@protoc_insertion_point(field_mutable:test.first.c)
  return c_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* first::release_c() {
  // @@protoc_insertion_point(field_release:test.first.c)
  clear_has_c();
  return c_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void first::set_allocated_c(::std::string* c) {
  if (c != NULL) {
    set_has_c();
  } else {
    clear_has_c();
  }
  c_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), c);
  // @@protoc_insertion_point(field_set_allocated:test.first.c)
}

// repeated uint32 d = 4;
inline int first::d_size() const {
  return d_.size();
}
inline void first::clear_d() {
  d_.Clear();
}
inline ::google::protobuf::uint32 first::d(int index) const {
  // @@protoc_insertion_point(field_get:test.first.d)
  return d_.Get(index);
}
inline void first::set_d(int index, ::google::protobuf::uint32 value) {
  d_.Set(index, value);
  // @@protoc_insertion_point(field_set:test.first.d)
}
inline void first::add_d(::google::protobuf::uint32 value) {
  d_.Add(value);
  // @@protoc_insertion_point(field_add:test.first.d)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
first::d() const {
  // @@protoc_insertion_point(field_list:test.first.d)
  return d_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
first::mutable_d() {
  // @@protoc_insertion_point(field_mutable_list:test.first.d)
  return &d_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace test

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2eproto__INCLUDED
