#!/usr/bin/env bash
subdir=("UsageEnvironment" "BasicUsageEnvironment" "groupsock" "liveMedia")
if [ ! -d "lib/live555" ];then
	mkdir -p "lib/live555"
fi
if [ ! -d "include/live555" ];then
	mkdir -p "include/live555"
fi

if [ $# -lt 1 ];then
	echo "need live555 path"
	exit -1
fi
echo $1
for i in ${subdir[*]};do
	cp -f $1/$i/*.a lib/live555/
	cp -f $1/$i/include/* include/live555/
done


