#export PKG_CONFIG_PATH=/home/francis/ssl/lib/pkgconfig
CXXFLAGS=-g -std=c++11
#CFLAGS+=`pkg-config --cflags libcrypto`
#LDLIBS=`pkg-config --libs libcrypto`
CC=$(CXX)
LDLIBS=
main:main.o creational_patterns.o structural_patterns.o behavioral_patterns.o

clean:
	rm -rf *.o main
